// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef PROTOBUF_msg_2eproto__INCLUDED
#define PROTOBUF_msg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace lm {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_2eproto();
void protobuf_AssignDesc_msg_2eproto();
void protobuf_ShutdownFile_msg_2eproto();

class helloworld;

// ===================================================================

class helloworld : public ::google::protobuf::Message {
 public:
  helloworld();
  virtual ~helloworld();

  helloworld(const helloworld& from);

  inline helloworld& operator=(const helloworld& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const helloworld& default_instance();

  void Swap(helloworld* other);

  // implements Message ----------------------------------------------

  helloworld* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const helloworld& from);
  void MergeFrom(const helloworld& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 uuid = 1;
  inline bool has_uuid() const;
  inline void clear_uuid();
  static const int kUuidFieldNumber = 1;
  inline ::google::protobuf::int32 uuid() const;
  inline void set_uuid(::google::protobuf::int32 value);

  // required string str_license = 2;
  inline bool has_str_license() const;
  inline void clear_str_license();
  static const int kStrLicenseFieldNumber = 2;
  inline const ::std::string& str_license() const;
  inline void set_str_license(const ::std::string& value);
  inline void set_str_license(const char* value);
  inline void set_str_license(const char* value, size_t size);
  inline ::std::string* mutable_str_license();
  inline ::std::string* release_str_license();
  inline void set_allocated_str_license(::std::string* str_license);

  // optional int32 opt_for_test = 3;
  inline bool has_opt_for_test() const;
  inline void clear_opt_for_test();
  static const int kOptForTestFieldNumber = 3;
  inline ::google::protobuf::int32 opt_for_test() const;
  inline void set_opt_for_test(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lm.helloworld)
 private:
  inline void set_has_uuid();
  inline void clear_has_uuid();
  inline void set_has_str_license();
  inline void clear_has_str_license();
  inline void set_has_opt_for_test();
  inline void clear_has_opt_for_test();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* str_license_;
  ::google::protobuf::int32 uuid_;
  ::google::protobuf::int32 opt_for_test_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_msg_2eproto();
  friend void protobuf_AssignDesc_msg_2eproto();
  friend void protobuf_ShutdownFile_msg_2eproto();

  void InitAsDefaultInstance();
  static helloworld* default_instance_;
};
// ===================================================================


// ===================================================================

// helloworld

// required int32 uuid = 1;
inline bool helloworld::has_uuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void helloworld::set_has_uuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void helloworld::clear_has_uuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void helloworld::clear_uuid() {
  uuid_ = 0;
  clear_has_uuid();
}
inline ::google::protobuf::int32 helloworld::uuid() const {
  return uuid_;
}
inline void helloworld::set_uuid(::google::protobuf::int32 value) {
  set_has_uuid();
  uuid_ = value;
}

// required string str_license = 2;
inline bool helloworld::has_str_license() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void helloworld::set_has_str_license() {
  _has_bits_[0] |= 0x00000002u;
}
inline void helloworld::clear_has_str_license() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void helloworld::clear_str_license() {
  if (str_license_ != &::google::protobuf::internal::kEmptyString) {
    str_license_->clear();
  }
  clear_has_str_license();
}
inline const ::std::string& helloworld::str_license() const {
  return *str_license_;
}
inline void helloworld::set_str_license(const ::std::string& value) {
  set_has_str_license();
  if (str_license_ == &::google::protobuf::internal::kEmptyString) {
    str_license_ = new ::std::string;
  }
  str_license_->assign(value);
}
inline void helloworld::set_str_license(const char* value) {
  set_has_str_license();
  if (str_license_ == &::google::protobuf::internal::kEmptyString) {
    str_license_ = new ::std::string;
  }
  str_license_->assign(value);
}
inline void helloworld::set_str_license(const char* value, size_t size) {
  set_has_str_license();
  if (str_license_ == &::google::protobuf::internal::kEmptyString) {
    str_license_ = new ::std::string;
  }
  str_license_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* helloworld::mutable_str_license() {
  set_has_str_license();
  if (str_license_ == &::google::protobuf::internal::kEmptyString) {
    str_license_ = new ::std::string;
  }
  return str_license_;
}
inline ::std::string* helloworld::release_str_license() {
  clear_has_str_license();
  if (str_license_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = str_license_;
    str_license_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void helloworld::set_allocated_str_license(::std::string* str_license) {
  if (str_license_ != &::google::protobuf::internal::kEmptyString) {
    delete str_license_;
  }
  if (str_license) {
    set_has_str_license();
    str_license_ = str_license;
  } else {
    clear_has_str_license();
    str_license_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 opt_for_test = 3;
inline bool helloworld::has_opt_for_test() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void helloworld::set_has_opt_for_test() {
  _has_bits_[0] |= 0x00000004u;
}
inline void helloworld::clear_has_opt_for_test() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void helloworld::clear_opt_for_test() {
  opt_for_test_ = 0;
  clear_has_opt_for_test();
}
inline ::google::protobuf::int32 helloworld::opt_for_test() const {
  return opt_for_test_;
}
inline void helloworld::set_opt_for_test(::google::protobuf::int32 value) {
  set_has_opt_for_test();
  opt_for_test_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace lm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_2eproto__INCLUDED
